source "https://api.berkshelf.com"
metadata

# TODO add dependency on openiaml.org once it's on version control
cookbook "openiaml.org",  path: "my-cookbooks/openiaml.org"

# TODO add dependency on openiaml.org once it's on version control
cookbook "index.jevon.org",  path: "my-cookbooks/index.jevon.org"

# TODO add dependency on openiaml.org once it's on version control
cookbook "hardening",  path: "my-cookbooks/hardening"
