name             'jevon.org'
maintainer       'Jevon Wright'
maintainer_email 'jevon@jevon.org'
license          'all_rights'
description      'Installs/Configures jevon.org'
long_description '...'
version          '0.1.0'
